import Home from "../pages/home";
import Head from "next/head";
import axios from "axios";

export default function HomeIndex({ categoryList, productList }) {
  return (
    <div className="min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon" href="favicon.ico"></link>
      </Head>
      <Home categoryList={categoryList} productList={productList} />
    </div>
  );
}
export const getServerSideProps = async () => {
  const res = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/categories`);
  const product = await axios.get(
    `${process.env.NEXT_PUBLIC_API_URL}/products`
  );
  return {
    props: {
      categoryList: res.data ? res.data : [],
      productList: product.data ? product.data : [],
    },
  };
};
